// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aynenacutguxaxeazpzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bmVuYWN1dGd1eGF4ZWF6cHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDg1NjgsImV4cCI6MjA2MTkyNDU2OH0.ln_mnT5j76TeCq_bMYSESGKujwXQ5-OHlEm7W0iEIvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);